name: Build

on:
  push:
    branches:
      - "main"
    paths:
      - "src/**"
      - "build/**"
      - ".github/actions/**"
      - ".github/workflows/build.yaml"

jobs:
  images-linux-amd64:
    runs-on: [self-hosted, Linux, X64, docker]
    steps:
      - name: Docker Hub login    
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: GHCR login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - uses: actions/checkout@master
      - uses: ./.github/actions/build    
    permissions:
      contents: read
      packages: write
